services:
  - type: web
    name: bloodbankmanagement
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py create_admin"
    startCommand: "gunicorn bloodbankmanagement.wsgi:application"
